language: node_js
node_js:
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn webpack-cli
  - yarn install

script:
  - yarn lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  script:
    - cd example
    - webpack
  local_dir: example/webpackReport
  on:
    branch: master
