language: node_js
node_js:
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - cd example/
  - yarn report

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: webpackReport
  on:
    branch: master
